### ISSUE TITLE
[Justitie] Cannot execute scraper

### ISSUE THREAD

**Issue by margelatu** [code4romania/czl-scrape#63]
Executed `pip install -r requirements.txt` and it checked out. Running the scraper, however, fails:

```
$ scrapy crawl just
2017-03-16 11:52:55 [scrapy.utils.log] INFO: Scrapy 1.3.3 started (bot: just)
2017-03-16 11:52:55 [scrapy.utils.log] INFO: Overridden settings: {'BOT_NAME': 'just', 'CONCURRENT_REQUESTS_PER_DOMAIN': 1, 'DOWNLOAD_DELAY': 5, 'HTTPCACHE_ENABLED': True, 'HTTPCACHE_EXPIRATION_SECS': 30, 'NEWSPIDER_MODULE': 'just.spiders', 'ROBOTSTXT_OBEY': True, 'SPIDER_MODULES': ['just.spiders'], 'USER_AGENT': 'code4romania (+http://www.code4.ro)'}
Traceback (most recent call last):
  File "/Users/imargela/.pyenv/versions/3.6.0/lib/python3.6/site-packages/scrapy/spiderloader.py", line 53, in load
    return self._spiders[spider_name]
KeyError: 'just'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/imargela/.pyenv/versions/3.6.0/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/Users/imargela/.pyenv/versions/3.6.0/lib/python3.6/site-packages/scrapy/cmdline.py", line 142, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/Users/imargela/.pyenv/versions/3.6.0/lib/python3.6/site-packages/scrapy/cmdline.py", line 88, in _run_print_help
    func(*a, **kw)
  File "/Users/imargela/.pyenv/versions/3.6.0/lib/python3.6/site-packages/scrapy/cmdline.py", line 149, in _run_command
    cmd.run(args, opts)
  File "/Users/imargela/.pyenv/versions/3.6.0/lib/python3.6/site-packages/scrapy/commands/crawl.py", line 57, in run
    self.crawler_process.crawl(spname, **opts.spargs)
  File "/Users/imargela/.pyenv/versions/3.6.0/lib/python3.6/site-packages/scrapy/crawler.py", line 162, in crawl
    crawler = self.create_crawler(crawler_or_spidercls)
  File "/Users/imargela/.pyenv/versions/3.6.0/lib/python3.6/site-packages/scrapy/crawler.py", line 190, in create_crawler
    return self._create_crawler(crawler_or_spidercls)
  File "/Users/imargela/.pyenv/versions/3.6.0/lib/python3.6/site-packages/scrapy/crawler.py", line 194, in _create_crawler
    spidercls = self.spider_loader.load(spidercls)
  File "/Users/imargela/.pyenv/versions/3.6.0/lib/python3.6/site-packages/scrapy/spiderloader.py", line 55, in load
    raise KeyError("Spider not found: {}".format(spider_name))
KeyError: 'Spider not found: just'
```

**Comment by margelatu** [comment]
Fixed, the spider name was actually `publication`. Updated instructions.
